### ISSUE TITLE
Is it possible to add support for Safari and Spotify?

### ISSUE THREAD

**Issue by nikivdev** [likewinter/genius-alfred-workflow#1]
I would love to have the same working but getting currently playing song from Spotfy instead and opening it in Safari.

Thank you a lot for making and sharing this.

**Comment by likewinter** [comment]
There was a mistake in the description: it will always open tab in your default browser, so if you are using Safari as default it will open a new tab in it. Spotify support added you can find new workflow in releases.

**Comment by nikivdev** [comment]
Thank you for the fast fix.

It always opens lyrics for [rap god](https://genius.com/Eminem-rap-god-lyrics) for me. Perhaps you can replicate it. Tried it for multiple songs already.

Thank you for any help.

**Comment by likewinter** [comment]
Oh, it's really weird behavior. Could you try to close both iTunes and Spotify, then open only one of them, start playing a song in it and use workflow? If it still fails can you write here the full name of tested song in the player and what lyrics you'll get in the browser?
Thanks.

**Comment by nikivdev** [comment]
Closed both Spotify and iTunes and tried again. Still gives me the rap god lyrics.

Here is the song I tried it on : 

![2017-01-08 at 04 04](https://cloud.githubusercontent.com/assets/6391776/21746971/9f432894-d557-11e6-937b-186c5a8c087f.png)

Alt J - Tessellate

And here is what opens in the browser : 

![2017-01-08 at 04 05](https://cloud.githubusercontent.com/assets/6391776/21746975/c3a0ea78-d557-11e6-9e98-ba332831b6ec.png)

**Comment by likewinter** [comment]
Thanks. I tried the same song in Spotify and it works perfectly for me, so right now I have no ideas how to repeat your behavior. This behavior is doubly weird for me because I'm using this workflow for about last 2 month several times a day and it only fails on track names with additional information like _remix 2009_ or _live version_ etc.
Right now I only can give you advice to completely remove workflow, download latest version from releases page and install it again. So I leave this issue for now open.

**Comment by nikivdev** [comment]
Tried it again. Here is an error I get in the debugger :  

`[2017-01-08 04:26:17][ERROR: action.script] /Users/nikivi/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Scripts/2AC40B13-3C98-4F35-A925-ED72C4D012AF:21:136: execution error: Error on line 2: Error: Message not understood. (-1708)`

![2017-01-08 at 04 27](https://cloud.githubusercontent.com/assets/6391776/21747052/c59816e6-d55a-11e6-8691-d0a67bc16f7b.png)

**Comment by likewinter** [comment]
OK, now I got it. The last thing I need to know do you use native Spotify desktop app or web version? I think I'll fix it in a day.

**Comment by nikivdev** [comment]
I use a client. :)

**Comment by likewinter** [comment]
@nikitavoloboev try new version from releases, maybe it'll work for you, at least there was a bug with player detection, but it only works for me when I'm trying to use workflow when no one app is playing music.

**Comment by nikivdev** [comment]
Nothing happens, as in no url opens at all.

**Comment by likewinter** [comment]
Now I see a problem: it can't detect current playing song in Spotify. Could you write your Mac OS version and I'll try to fix it tomorrow, right now I need to sleep :)

**Comment by nikivdev** [comment]
Yes, of course. 

10.11.6

**Comment by likewinter** [comment]
Can you try this version, maybe it's because of old version of Mac OS has some limitation for using JXA in AppleScripts, so I modified it to be compatible with old version [Genius.zip](https://github.com/likewinter/genius-alfred-workflow/files/691884/Genius.zip)

**Comment by nikivdev** [comment]
That too doesn't work :(

**Comment by likewinter** [comment]
@nikitavoloboev you can try the new version, I rewrite it in AppleScript which is more conservative and predictable as a language for writing scripts, so maybe the problem will go away.

**Comment by nikivdev** [comment]
@likewinter thank you, this worked perfectly

**Comment by nikivdev** [comment]
It is however not accurate often. For example listening to this song : 

![2017-01-08 at 16 18](https://cloud.githubusercontent.com/assets/6391776/21750887/245501c2-d5be-11e6-8b77-9de0f8f99414.png)

Brings this page :  https://genius.com/Tv-show-soundtracks-music-used-in-tv-shows-week-of-7-27-15-lyrics

**Comment by likewinter** [comment]
Yep, I know, because it takes the first result from search and Genius has problem with search relevance, but this kind of problem is not hard to fix, I'll make a new issue for it
